# Generated by Django 6.0.1 on 2026-01-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
