# Generated by Django 6.0.1 on 2026-01-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_tilte',
            new_name='blog_title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='iamge',
            new_name='image',
        ),
    ]
