# Generated by Django 6.0.1 on 2026-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_tilte_blog_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
