# Generated by Django 6.0.1 on 2026-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammange',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/staff'),
        ),
    ]
